export const REQUEST_CREATE_USER = "REQUEST_CREATE_USER";
export const RECEIVE_CREATE_USER = "RECEIVE_CREATE_USER";
export const FAILURE_CREATE_USER = "FAILURE_CREATE_USER";

export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";
export const FAILURE_LOGIN = "FAILURE_LOGIN";

export const REQUEST_LOGOUT = "REQUEST_LOGOUT";
export const RECEIVE_LOGOUT = "RECEIVE_LOGOUT";